name: Bump flake.lock

on:
  schedule:
    - cron: "0 1 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Install Nix
        uses: cachix/install-nix-action@v25

      - name: Update flake.lock
        run: nix flake update

      - name: Commit changes to flake.lock
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Bump flake.lock
          branch: main
          commit_options: '--no-verify --signoff'
          file_pattern: flake.lock
          commit_user_name: Flake Bot # defaults to "GitHub Actions"
          #commit_user_email: my-github-actions-bot@example.org # defaults to "actions@github.com"
          commit_author: Flake Bot <actions@github.com> # defaults to author of the commit that triggered the run
          skip_dirty_check: false    
          skip_fetch: true
